version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aftas
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
  aftasbackend:
    image: aftasbackend:v1
    container_name: aftasbackend
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mysql
#  aftasfrontend:
#    image: karimelaoumari/aftasfront:v1
#    container_name: aftasfront
#    ports:
#      - "4200:80"
#    depends_on:
#      - aftasbackendversion: '3'
